#!/bin/bash

# Agent launch script generator
# Creates individual launch scripts for each agent

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTS_DIR="$(dirname "$SCRIPT_DIR")"
SCRIPTS_DIR="$SCRIPT_DIR/agents"

# Create agents scripts directory
mkdir -p "$SCRIPTS_DIR"

echo "🤖 Creating individual agent launch scripts..."

# Function to create launch script for an agent
create_agent_script() {
    local agent_name="$1"
    local agent_dir="$2"
    
    cat > "$SCRIPTS_DIR/launch_${agent_name}.sh" << EOF
#!/bin/bash

# Launch script for $agent_name
# Auto-generated by create_agent_scripts.sh

AGENT_DIR="$agent_dir"
AGENT_NAME="$agent_name"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "\${YELLOW}[\$AGENT_NAME]${NC} \$1"; }
log_success() { echo -e "\${GREEN}[\$AGENT_NAME]${NC} \$1"; }
log_error() { echo -e "\${RED}[\$AGENT_NAME]${NC} \$1"; }

# Check if agent directory exists
if [ ! -d "\$AGENT_DIR" ]; then
    log_error "Agent directory not found: \$AGENT_DIR"
    exit 1
fi

cd "\$AGENT_DIR"

# Look for main file
MAIN_FILE=""
if [ -f "main.py" ]; then
    MAIN_FILE="main.py"
elif [ -f "app.py" ]; then
    MAIN_FILE="app.py"
elif [ -f "agent.py" ]; then
    MAIN_FILE="agent.py"
elif [ -f "run.py" ]; then
    MAIN_FILE="run.py"
elif [ -f "\${AGENT_NAME}.py" ]; then
    MAIN_FILE="\${AGENT_NAME}.py"
else
    # Find the first Python file
    MAIN_FILE=\$(find . -name "*.py" -type f | head -1)
fi

if [ -z "\$MAIN_FILE" ]; then
    log_error "No Python main file found in \$AGENT_DIR"
    exit 1
fi

# Install requirements if present
if [ -f "requirements.txt" ]; then
    log_info "Installing requirements..."
    pip install --user -r requirements.txt
fi

# Set up environment variables
export PYTHONPATH="\$AGENT_DIR:\$PYTHONPATH"

# Configure for local AI if no API keys are set
if [ -z "\$OPENAI_API_KEY" ]; then
    export OPENAI_BASE_URL="http://localhost:11434/v1"
    export OPENAI_API_KEY="ollama"
    log_info "Using Ollama as default provider"
fi

# Launch the agent
log_info "Launching \$AGENT_NAME..."
log_info "Main file: \$MAIN_FILE"
log_info "Working directory: \$AGENT_DIR"

python "\$MAIN_FILE" "\$@"
EOF

    chmod +x "$SCRIPTS_DIR/launch_${agent_name}.sh"
    echo "  ✅ Created launch script for $agent_name"
}

# Function to create stop script for an agent
create_agent_stop_script() {
    local agent_name="$1"
    
    cat > "$SCRIPTS_DIR/stop_${agent_name}.sh" << EOF
#!/bin/bash

# Stop script for $agent_name

AGENT_NAME="$agent_name"

echo "🛑 Stopping \$AGENT_NAME..."

# Find and kill processes related to this agent
pgrep -f "python.*$agent_name" | xargs -r kill

echo "✅ \$AGENT_NAME stopped"
EOF

    chmod +x "$SCRIPTS_DIR/stop_${agent_name}.sh"
}

# Scan for agents and create scripts
agent_count=0

for dir in "$AGENTS_DIR"/*; do
    if [ -d "$dir" ]; then
        dir_name=$(basename "$dir")
        
        # Skip certain directories
        if [[ "$dir_name" == "master-agent-menu" || "$dir_name" == "web-interface" || "$dir_name" == "scripts" || "$dir_name" == "."* || "$dir_name" == "~"* ]]; then
            continue
        fi
        
        # Check if it contains Python files or looks like an agent
        if find "$dir" -name "*.py" -type f | grep -q .; then
            create_agent_script "$dir_name" "$dir"
            create_agent_stop_script "$dir_name"
            agent_count=$((agent_count + 1))
        fi
    fi
done

# Create a master launch script
cat > "$SCRIPTS_DIR/launch_all_agents.sh" << 'EOF'
#!/bin/bash

# Launch all agents script

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "🚀 Launching all agents..."

# Launch each agent in background
for script in "$SCRIPTS_DIR"/launch_*.sh; do
    if [ -f "$script" ] && [[ "$(basename "$script")" != "launch_all_agents.sh" ]]; then
        agent_name=$(basename "$script" .sh | sed 's/launch_//')
        echo "Starting $agent_name..."
        "$script" &
        sleep 2
    fi
done

echo "✅ All agents launched"
echo "Use stop_all_agents.sh to stop all agents"
EOF

# Create a master stop script
cat > "$SCRIPTS_DIR/stop_all_agents.sh" << 'EOF'
#!/bin/bash

# Stop all agents script

echo "🛑 Stopping all agents..."

# Stop all agent processes
pkill -f "python.*agent"

echo "✅ All agents stopped"
EOF

chmod +x "$SCRIPTS_DIR/launch_all_agents.sh"
chmod +x "$SCRIPTS_DIR/stop_all_agents.sh"

echo
echo "📁 Created $agent_count agent scripts in $SCRIPTS_DIR/"
echo "   🚀 Use launch_all_agents.sh to start all agents"
echo "   🛑 Use stop_all_agents.sh to stop all agents"
echo "   🎯 Use launch_<agent_name>.sh to start individual agents"
echo