#!/bin/bash

# Launch script for python-local-ai-agent
# Auto-generated by create_agent_scripts.sh

AGENT_DIR="/home/runner/work/ottomator-agents/ottomator-agents/python-local-ai-agent"
AGENT_NAME="python-local-ai-agent"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${YELLOW}[$AGENT_NAME] $1"; }
log_success() { echo -e "${GREEN}[$AGENT_NAME] $1"; }
log_error() { echo -e "${RED}[$AGENT_NAME] $1"; }

# Check if agent directory exists
if [ ! -d "$AGENT_DIR" ]; then
    log_error "Agent directory not found: $AGENT_DIR"
    exit 1
fi

cd "$AGENT_DIR"

# Look for main file
MAIN_FILE=""
if [ -f "main.py" ]; then
    MAIN_FILE="main.py"
elif [ -f "app.py" ]; then
    MAIN_FILE="app.py"
elif [ -f "agent.py" ]; then
    MAIN_FILE="agent.py"
elif [ -f "run.py" ]; then
    MAIN_FILE="run.py"
elif [ -f "${AGENT_NAME}.py" ]; then
    MAIN_FILE="${AGENT_NAME}.py"
else
    # Find the first Python file
    MAIN_FILE=$(find . -name "*.py" -type f | head -1)
fi

if [ -z "$MAIN_FILE" ]; then
    log_error "No Python main file found in $AGENT_DIR"
    exit 1
fi

# Install requirements if present
if [ -f "requirements.txt" ]; then
    log_info "Installing requirements..."
    pip install --user -r requirements.txt
fi

# Set up environment variables
export PYTHONPATH="$AGENT_DIR:$PYTHONPATH"

# Configure for local AI if no API keys are set
if [ -z "$OPENAI_API_KEY" ]; then
    export OPENAI_BASE_URL="http://localhost:11434/v1"
    export OPENAI_API_KEY="ollama"
    log_info "Using Ollama as default provider"
fi

# Launch the agent
log_info "Launching $AGENT_NAME..."
log_info "Main file: $MAIN_FILE"
log_info "Working directory: $AGENT_DIR"

python "$MAIN_FILE" "$@"
